logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

#spring:
#  rabbitmq:
#    host: rabbitmq

spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    stream:
      kafka:
        binder:
          brokers: peer1:9092
          zk-nodes: peer1:2181