logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-node1:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    stream:
      kafka:
        binder:
          brokers: eureka-node1:9092
          zk-nodes: eureka-node1:2181

management:
  security:
    enabled: false