spring:
  data:
    mongodb:
      host: mongodb
      username: user
      password: root #${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  context-path: /uaa
  port: 5000
